name = "ImageAnnotations"
uuid = "76a96b56-f16f-11e8-3761-3967fdcf98d3"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.6.5"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
GeometryBasics = "0.4.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
