name = "ImageAnnotations"
uuid = "76a96b56-f16f-11e8-3761-3967fdcf98d3"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.6.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"

[compat]
ColorTypes = "0.11.0"
GeometryBasics = "0.4.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
