name = "ObjectDetectors"
uuid = "76a96b56-f16f-11e8-3761-3967fdcf98d3"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.3.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
